### ISSUE TITLE
newSurface: 1, (iokit/common) invalid argument

### ISSUE THREAD

**Issue by FoxRunTime** [Siguza/cuck00#1]
Occurs on macOS 10.14.6 (18G103), terminal output below:

As standard (admin) user:

```
➜  ~ cuck00
port: 120b, (os/kern) successful
service: 2703
client: 2807, (os/kern) successful
newSurface: 1, (iokit/common) invalid argument
port addr: 0x0
```

As root:
```
sh-3.2# cuck00
port: 1303, (os/kern) successful
service: a07
client: b07, (os/kern) successful
newSurface: 1, (iokit/common) invalid argument
port addr: 0x0
```

Compiled binary is in `/usr/bin`, but the same error occurs when I run it from the folder immediately after running `make`.

**Comment by Siguza** [comment]
Change line 58 to:

    #define IOSURFACE_CREATE_OUTSIZE 0x8d0

**Comment by FoxRunTime** [comment]
Nice, that worked! Thanks!
